Flourescence spectroscopy data anlysis and tools

In [10]:
# import some key libraies
    
    import os
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.optimize import curve_fit
    from numpy import log as ln

IndentationError: unexpected indent (2505223400.py, line 3)

In [1]:
pwd

'C:\\Users\\hwbst6\\OneDrive - Sheffield Hallam University\\StudentProjects\\Student projects 2022_23\\MSc\\Bhargav\\140623'

In [3]:
cd ..

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc

In [4]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc

12/06/2023  11:23    <DIR>          .
12/06/2023  11:23    <DIR>          ..
24/05/2023  14:56           616,573 40-876961736_R1.pdf
29/06/2023  10:42    <DIR>          Aleena
23/05/2023  16:19            33,518 Aleena Raju Project Proposal 2023.docx
27/03/2023  11:37            31,768 ALRP Lit Review Feedback Sheet(1).docx
23/05/2023  16:25            47,093 ALRP Research Project Proposal 2023.docx
04/07/2023  09:33    <DIR>          Bhargav
23/05/2023  16:26            47,224 Bhargav Project Proposal 2023.docx
05/06/2023  16:56            89,333 Bhargav UREC1 No Human Participants 2022-23v2.docx
24/05/2023  14:48            69,804 ed6d4038-b1f9-4fcf-9fa4-035dd759fc09-OrderPackageReport.pdf
25/05/2023  16:02             2,194 gc_66-502902-AF-20223_fullgc_2023-05-25-15-58-46.xls
26/06/2023  18:12    <DIR>          MML
09/02/2023  14:37            15,598 MSc projects.docx
13/06/2023  08:35    <DIR>          Nivedh
27/03/2023  14:09            25,791 Nivedh ALRP Lit Review Feedback Sheet(1).docx
23/05/2023  16:31            47,437 Nivedh Lal Project Proposal 2023.docx
27/03/2023  11:38            31,915 Raju AleenaALRP Lit Review Feedback Sheet(1).docx
15/06/2023  14:15    <DIR>          Research group
03/04/2023  16:41    <DIR>          RNA kit instructions
12/05/2023  17:01            45,563 Students allocations.xlsx
              13 File(s)      1,103,811 bytes
               8 Dir(s)  145,294,450,688 bytes free

In [6]:
cd MML

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML

In [7]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML

26/06/2023  18:12    <DIR>          .
26/06/2023  18:12    <DIR>          ..
24/05/2023  11:04             1,422 24052023_1.csv
08/06/2023  10:56    <DIR>          Fluorescence_data
24/05/2023  10:57             1,106 knn_settings24052023_1.txt.xml
17/05/2023  11:43                 0 New Text Document.txt
26/06/2023  16:11    <DIR>          refresher tutorial
08/06/2023  10:56            12,597 RNAfluor22Train.csv
26/06/2023  18:01           121,463 RNAUVvis22Train _II.csv
17/05/2023  11:49           123,595 RNAUVvis22Train.csv
24/05/2023  11:24           123,595 RNAUVvis22Train_2.csv
26/06/2023  15:01    <DIR>          UV_vis
26/06/2023  17:43           133,157 uvvis_unk-260623.csv
26/06/2023  18:12           130,367 uvvis_unk-260623_II.csv
               9 File(s)        647,302 bytes
               5 Dir(s)  145,294,917,632 bytes free

In [112]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from numpy import log as ln

flu_inp = pd.read_excel('RNA QUANTIFLUOR_006 20-7-22.xlsx', sheet_name = 'TRno3622')




#flu_inp = flu_inp.sort_index().reset_index(drop=True)
row_num = 0
x = 4
while row_num < x:
    flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=row_num)
    row_num = row_num + 1

flu_inp = flu_inp.DataFrame.drop("User: USER",axis=0, index=6)

#flu_inp = pd.DataFrame.drop(flu_inp,axis=1, index=1)
    
#flu_inp.loc[1] = flu_inp.loc[1].astype(str)
    
flu_inp = flu_inp.sort_index().reset_index(drop=True)

#flu_inp.loc[2.5] = flu_inp.loc[0] + flu_inp.loc[1]
#flu_inp = flu_inp.sort_index().reset_index(drop=True)
print(flu_inp.loc[9])
print(type(flu_inp.iloc[3,4]))

flu_inp

AttributeError: 'DataFrame' object has no attribute 'DataFrame'

In [14]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML

26/06/2023  18:12    <DIR>          .
26/06/2023  18:12    <DIR>          ..
24/05/2023  11:04             1,422 24052023_1.csv
08/06/2023  10:56    <DIR>          Fluorescence_data
24/05/2023  10:57             1,106 knn_settings24052023_1.txt.xml
17/05/2023  11:43                 0 New Text Document.txt
26/06/2023  16:11    <DIR>          refresher tutorial
08/06/2023  10:56            12,597 RNAfluor22Train.csv
26/06/2023  18:01           121,463 RNAUVvis22Train _II.csv
17/05/2023  11:49           123,595 RNAUVvis22Train.csv
24/05/2023  11:24           123,595 RNAUVvis22Train_2.csv
26/06/2023  15:01    <DIR>          UV_vis
26/06/2023  17:43           133,157 uvvis_unk-260623.csv
26/06/2023  18:12           130,367 uvvis_unk-260623_II.csv
               9 File(s)        647,302 bytes
               5 Dir(s)  145,267,142,656 bytes free

In [15]:
cd Fluorescence_data

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML\Fluorescence_data

In [287]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from numpy import log as ln

flu_inp = pd.read_excel('RNA QUANTIFLUOR_006 20-7-22.xlsx', sheet_name = 'TRno3622')

flu_inp= pd.DataFrame.transpose(flu_inp)

flu_inp = flu_inp.drop(axis=1, columns=[0,1,2,3])


#flu_inp.sort_index()
flu_inp = flu_inp.reset_index(drop=True)

flu_inp.iloc[0:,1] = flu_inp.iloc[0:,1].astype(str)

flu_inp.iloc[0:,2] = flu_inp.iloc[0:,0] + flu_inp.iloc[0:,1]

#spec_tranf['spectra bg_sub'] = spec_tranf.iloc[0:,2] - spec_tranf.iloc[0:,1]

flu_inp = flu_inp.drop(axis=1, columns=[4,5])

flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=0)

flu_inp.insert(1, "RNA", "")



# Design concentration

stk_conc = 500
exp_reps = 3
dil_fct = 2
std_no = 8

n=0
#conc fill
while n <= std_no -1:
    n_reps = 1
    while n_reps <= exp_reps:
        tran_rep = (n * exp_reps + n_reps )
        flu_inp.iloc[(tran_rep),1] =  stk_conc / 2**(n) 
        #print((n+n_reps-1))
        #print("n_reps = " + str(n_reps))
        n_reps = n_reps +1
    n = n + 1
    #print(n)
    
mml_format = pd.DataFrame(flu_inp.iloc[0:(1 +exp_reps*std_no),0:])
mml_format.iloc[0,1] = mml_format.columns[1]          
mml_format.insert(0, "protein", "0")
mml_format.insert(3, "Chem", "rna")
mml_format.insert(3, "Sample ID", "")

n=1
#sample ID fill
while n <= std_no * exp_reps:
    mml_format.iloc[n,3] =  mml_format.iloc[n,1] + 'TRno3622'
    n = n + 1
    
# title fill
n=0
while n <= 4:
    mml_format.iloc[0,n] =  mml_format.columns[n]
    n = n + 1

mml_format = pd.DataFrame.drop(mml_format,axis=1, columns = 6)
    
mf_lst = list(mml_format.iloc[0,0:])

mml_format.rename(columns=mml_format.iloc[0,0:], inplace=True)
mml_format = mml_format.reset_index(drop=True)
mml_format = pd.DataFrame.drop(mml_format, axis=0, index=0)
mml_format.to_csv("mml_format" + ".csv",index=False)
#mml_format

,protein,RNA,Sample ID,Chem,517,519,521,523,525,527,...,703,705,707,709,711,713,715,717,719,721
1,0,500.0,A1TRno3622,rna,7943,9307,11009,12821,14895,16975,...,2046,1840,1855,1716,1803,1835,1612,1595,1514,1746
2,0,500.0,A2TRno3622,rna,7670,8965,10656,12408,14314,16268,...,2076,1969,1855,1793,1887,1606,1662,1485,1574,1679
3,0,500.0,A3TRno3622,rna,7391,8668,10324,12044,13873,15809,...,2135,2001,1820,1793,1761,1698,1662,1705,1877,1612
4,0,250.0,B1TRno3622,rna,2788,3211,3764,4394,5075,5772,...,1097,1065,1050,1182,1132,1101,1058,1210,1150,1209
5,0,250.0,B2TRno3622,rna,2612,3009,3523,4062,4733,5401,...,1157,1162,1155,1182,1132,1147,1058,1265,1150,1209
6,0,250.0,B3TRno3622,rna,2633,2972,3512,4097,4726,5394,...,1127,1130,1050,1068,1007,1055,1007,990,1150,1142
7,0,125.0,C1TRno3622,rna,1428,1593,1851,2104,2432,2716,...,801,807,805,877,755,826,856,825,908,1008
8,0,125.0,C2TRno3622,rna,1327,1439,1692,1929,2180,2454,...,801,742,735,839,839,734,907,880,848,1008
9,0,125.0,C3TRno3622,rna,1481,1643,1907,2236,2576,2957,...,801,871,875,877,839,872,907,935,1029,1008
10,0,62.5,D1TRno3622,rna,1198,1320,1497,1689,1904,2144,...,563,581,595,572,545,642,806,770,727,873
11,0,62.5,D2TRno3622,rna,891,937,1065,1196,1324,1470,...,504,613,595,572,671,688,705,605,787,739
12,0,62.5,D3TRno3622,rna,912,950,1089,1219,1369,1506,...,563,613,560,610,629,780,806,770,666,873
13,0,31.25,E1TRno3622,rna,762,777,875,960,1029,1145,...,445,387,490,496,503,551,554,660,727,806
14,0,31.25,E2TRno3622,rna,734,752,829,905,1005,1085,...,504,516,595,572,545,597,655,715,727,873
15,0,31.25,E3TRno3622,rna,775,761,853,942,1035,1163,...,504,581,560,610,587,642,756,715,848,873
16,0,15.625,F1TRno3622,rna,1396,1418,1513,1627,1716,1799,...,475,516,455,496,545,597,554,660,727,739
17,0,15.625,F2TRno3622,rna,753,744,795,850,915,989,...,475,420,525,458,629,597,655,660,727,739
18,0,15.625,F3TRno3622,rna,630,622,665,717,774,838,...,415,516,455,534,545,551,604,605,727,806
19,0,7.8125,G1TRno3622,rna,581,577,616,665,718,773,...,386,420,455,458,503,551,604,550,727,739
20,0,7.8125,G2TRno3622,rna,611,579,610,672,711,752,...,415,452,525,572,545,597,655,550,605,672
21,0,7.8125,G3TRno3622,rna,599,579,617,663,697,746,...,415,420,420,496,503,459,554,660,666,739
22,0,3.90625,H1TRno3622,rna,554,515,561,602,626,657,...,386,420,420,420,503,459,554,605,727,672
23,0,3.90625,H2TRno3622,rna,578,541,577,610,632,655,...,386,355,455,458,461,505,554,605,666,739
24,0,3.90625,H3TRno3622,rna,2824,3019,3347,3700,4027,4362,...,563,581,595,572,629,642,756,605,787,873

In [209]:
pwd

'C:\\Users\\hwbst6\\OneDrive - Sheffield Hallam University\\StudentProjects\\Student projects 2022_23\\MSc\\MML\\Fluorescence_data'

In [248]:
stk_conc = 100
exp_reps = 3
dil_fct = 2
std_no = 8

n=0
#n_reps = 1
while n <= std_no -1:
    n_reps = 1
    while n_reps <= exp_reps:
        tran_rep = (n * exp_reps + n_reps )
         
        print(tran_rep)
        #print(n)
        n_reps = n_reps +1
    n = n + 1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24

In [288]:
pwd

'C:\\Users\\hwbst6\\OneDrive - Sheffield Hallam University\\StudentProjects\\Student projects 2022_23\\MSc\\MML\\Fluorescence_data'

In [289]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML\Fluorescence_data

04/07/2023  17:06    <DIR>          .
04/07/2023  17:06    <DIR>          ..
05/07/2023  14:19            12,641 mml_format.csv
17/09/2022  15:00            99,086 RNA QUANTIFLUOR_005.csv
08/06/2023  10:56           152,595 RNA QUANTIFLUOR_006 20-7-22.xlsx
17/09/2022  15:00            31,619 RNA Quantifluor-001.xlsx
17/09/2022  15:00            64,864 RNA Quantifluor-003- 5-7-22.xlsx
17/09/2022  15:00           110,741 RNA Quantifluor-007 27-7-2022.xlsx
               6 File(s)        471,546 bytes
               2 Dir(s)  143,581,134,848 bytes free

In [332]:
#Second attemp at processing Akhilas flouresence data

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from numpy import log as ln

#load in plate reader output

flu_inp = pd.read_excel('RNA QUANTIFLUOR_006 20-7-22.xlsx', sheet_name = 'TRno3622')


#transpose and remove some columns, these may need changeing
flu_inp= pd.DataFrame.transpose(flu_inp)
flu_inp = flu_inp.drop(axis=1, columns=[0,1,2,3])


#flu_inp.sort_index()
flu_inp = flu_inp.reset_index(drop=True)

#build well name and remove related columns
flu_inp.iloc[0:,1] = flu_inp.iloc[0:,1].astype(str)
flu_inp.iloc[0:,2] = flu_inp.iloc[0:,0] + flu_inp.iloc[0:,1]
flu_inp = flu_inp.drop(axis=1, columns=[4,5])
flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=0)

flu_inp.insert(1, "RNA", "")

flu_inp.iloc[0,1] = flu_inp.columns[1]          
flu_inp.insert(0, "protein", "0")
flu_inp.insert(3, "Chem", "rna")
flu_inp.insert(3, "Sample ID", "")

n=1
#sample ID fill
while n <= 69:
    flu_inp.iloc[n,3] =  flu_inp.iloc[n,1] + 'TRno3622'
    n = n + 1
    
# title fill
n=0
while n <= 4:
    flu_inp.iloc[0,n] =  flu_inp.columns[n]
    n = n + 1

flu_inp = pd.DataFrame.drop(flu_inp,axis=1, columns = 6)  

mf_lst = list(flu_inp.iloc[0,0:])

flu_inp.rename(columns=flu_inp.iloc[0,0:], inplace=True)
flu_inp = flu_inp.reset_index(drop=True)
flu_inp = pd.DataFrame.drop(flu_inp, axis=0, index=0)
flu_inp = flu_inp.reset_index(drop=True)
flu_inp.iloc[0:,1] = 0

flu_inp.iloc[24:27,3] = "blank"
flu_inp.iloc[27:69,0:2] = "unk"

# Design concentration

stk_conc = 500
exp_reps = 3
dil_fct = 2
std_no = 7

n=0
#conc fill
while n <= std_no -1:
    n_reps = 1
    while n_reps <= exp_reps:
        tran_rep = (n * exp_reps + n_reps )
        flu_inp.iloc[(tran_rep-1),1] =  stk_conc / 2**(n) 
        #print((n+n_reps-1))
        #print("n_reps = " + str(n_reps))
        n_reps = n_reps +1
    n = n + 1

flu_train = pd.DataFrame(flu_inp.iloc[0:24,0:])        

flu_train.to_csv("flu_train_001" + ".csv",index=False)

flu_unk = pd.DataFrame(flu_inp.iloc[24:,0:]) 

flu_unk.to_csv("flu_unk_001" + ".csv",index=False)

print(flu_inp.loc[23:27])
flu_train

   protein  RNA   Sample ID   Chem    517    519    521    523    525    527  \
23       0    0  H3TRno3622    rna   2824   3019   3347   3700   4027   4362
24       0    0  A4TRno3622  blank   6677   7674   9050  10413  11921  13468
25       0    0  A5TRno3622  blank   5662   6491   7615   8875  10143  11489
26       0    0  A6TRno3622  blank   5784   6639   7847   9100  10469  11830
27     unk  unk  B4TRno3622    rna  15369  18074  21575  25125  29065  33227

    ...   703   705   707   709   711   713   715   717   719   721
23  ...   563   581   595   572   629   642   756   605   787   873
24  ...  1512  1420  1260  1297  1216  1285  1209  1320  1332  1343
25  ...  1394  1452  1295  1335  1216  1285  1360  1375  1453  1478
26  ...  1424  1388  1365  1297  1174  1331  1360  1430  1332  1411
27  ...  2906  2647  2520  2479  2391  2340  2166  2255  2119  2015

[5 rows x 107 columns]

,protein,RNA,Sample ID,Chem,517,519,521,523,525,527,...,703,705,707,709,711,713,715,717,719,721
0,0,500.0,A1TRno3622,rna,7943,9307,11009,12821,14895,16975,...,2046,1840,1855,1716,1803,1835,1612,1595,1514,1746
1,0,500.0,A2TRno3622,rna,7670,8965,10656,12408,14314,16268,...,2076,1969,1855,1793,1887,1606,1662,1485,1574,1679
2,0,500.0,A3TRno3622,rna,7391,8668,10324,12044,13873,15809,...,2135,2001,1820,1793,1761,1698,1662,1705,1877,1612
3,0,250.0,B1TRno3622,rna,2788,3211,3764,4394,5075,5772,...,1097,1065,1050,1182,1132,1101,1058,1210,1150,1209
4,0,250.0,B2TRno3622,rna,2612,3009,3523,4062,4733,5401,...,1157,1162,1155,1182,1132,1147,1058,1265,1150,1209
5,0,250.0,B3TRno3622,rna,2633,2972,3512,4097,4726,5394,...,1127,1130,1050,1068,1007,1055,1007,990,1150,1142
6,0,125.0,C1TRno3622,rna,1428,1593,1851,2104,2432,2716,...,801,807,805,877,755,826,856,825,908,1008
7,0,125.0,C2TRno3622,rna,1327,1439,1692,1929,2180,2454,...,801,742,735,839,839,734,907,880,848,1008
8,0,125.0,C3TRno3622,rna,1481,1643,1907,2236,2576,2957,...,801,871,875,877,839,872,907,935,1029,1008
9,0,62.5,D1TRno3622,rna,1198,1320,1497,1689,1904,2144,...,563,581,595,572,545,642,806,770,727,873
10,0,62.5,D2TRno3622,rna,891,937,1065,1196,1324,1470,...,504,613,595,572,671,688,705,605,787,739
11,0,62.5,D3TRno3622,rna,912,950,1089,1219,1369,1506,...,563,613,560,610,629,780,806,770,666,873
12,0,31.25,E1TRno3622,rna,762,777,875,960,1029,1145,...,445,387,490,496,503,551,554,660,727,806
13,0,31.25,E2TRno3622,rna,734,752,829,905,1005,1085,...,504,516,595,572,545,597,655,715,727,873
14,0,31.25,E3TRno3622,rna,775,761,853,942,1035,1163,...,504,581,560,610,587,642,756,715,848,873
15,0,15.625,F1TRno3622,rna,1396,1418,1513,1627,1716,1799,...,475,516,455,496,545,597,554,660,727,739
16,0,15.625,F2TRno3622,rna,753,744,795,850,915,989,...,475,420,525,458,629,597,655,660,727,739
17,0,15.625,F3TRno3622,rna,630,622,665,717,774,838,...,415,516,455,534,545,551,604,605,727,806
18,0,7.8125,G1TRno3622,rna,581,577,616,665,718,773,...,386,420,455,458,503,551,604,550,727,739
19,0,7.8125,G2TRno3622,rna,611,579,610,672,711,752,...,415,452,525,572,545,597,655,550,605,672
20,0,7.8125,G3TRno3622,rna,599,579,617,663,697,746,...,415,420,420,496,503,459,554,660,666,739
21,0,0,H1TRno3622,rna,554,515,561,602,626,657,...,386,420,420,420,503,459,554,605,727,672
22,0,0,H2TRno3622,rna,578,541,577,610,632,655,...,386,355,455,458,461,505,554,605,666,739
23,0,0,H3TRno3622,rna,2824,3019,3347,3700,4027,4362,...,563,581,595,572,629,642,756,605,787,873

In [58]:
#third attemp at processing Akhilas flouresence data this one has protien in it

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from numpy import log as ln

#load in plate reader output

flu_inp = pd.read_excel('RNA Quantifluor-003- 5-7-22.xlsx', sheet_name = 'TRno3575')

#transpose and remove some columns, these may need changeing
flu_inp= pd.DataFrame.transpose(flu_inp)
flu_inp = flu_inp.drop(axis=1, columns=[0,1,2,3])

#flu_inp.sort_index()
flu_inp = flu_inp.reset_index(drop=True)

#build well name and remove related columns
flu_inp.iloc[0:,1] = flu_inp.iloc[0:,1].astype(str)
flu_inp.iloc[0:,2] = flu_inp.iloc[0:,0].astype(str) + flu_inp.iloc[0:,1].astype(str)
flu_inp = flu_inp.drop(axis=1, columns=[4,5])
flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=0)

flu_inp.insert(1, "RNA", "")

flu_inp.iloc[0,1] = flu_inp.columns[1]          
flu_inp.insert(0, "protein", "0")
flu_inp.insert(3, "Chem", "rna")
flu_inp.insert(3, "Sample ID", "")

n=1
#sample ID fill
while n <= 36: # does this number need to be a varible
    flu_inp.iloc[n,3] =  flu_inp.iloc[n,1] + 'TRno3648'
    n = n + 1

# title fill
n=0
while n <= 4:
    flu_inp.iloc[0,n] =  flu_inp.columns[n]
    n = n + 1   
    
flu_inp = pd.DataFrame.drop(flu_inp,axis=1, columns = 6)  

flu_inp.rename(columns=flu_inp.iloc[0,0:], inplace=True) # set row 0 as col titles
flu_inp = flu_inp.reset_index(drop=True)
flu_inp = pd.DataFrame.drop(flu_inp, axis=0, index=0)
flu_inp = flu_inp.reset_index(drop=True)
flu_inp.iloc[0:,1] = 0

#Design concentration

stk_conc = 500
exp_reps = 3
dil_fct = 2
std_no = 7

n=0
#conc fill
while n <= std_no -1:
    n_reps = 1
    while n_reps <= exp_reps:
        tran_rep = (n * exp_reps + n_reps )
        flu_inp.iloc[(tran_rep-1),1] =  stk_conc / 2**(n)
        flu_inp.iloc[(tran_rep-1),0] =  stk_conc / 2**(n)
        n_reps = n_reps +1
    n = n + 1


flu_inp.iloc[21:24,3] = "blank"
flu_inp.iloc[24:72,0:2] = "unk"
#prorna

flu_inp.iloc[0:21,3] = "prorna"

print(flu_inp.loc[20:27])
flu_train = pd.DataFrame(flu_inp.iloc[0:24,0:])  
flu_train.to_csv("flu_train_004" + ".csv",index=False)
flu_inp.to_csv("flu_TRno3575" + ".csv",index=False)
flu_inp

   protein     RNA   Sample ID    Chem    517    519    521    523    525  \
20  7.8125  7.8125  G3TRno3648  prorna    675    659    738    788    871
21       0       0  H1TRno3648   blank    546    533    568    605    649
22       0       0  H2TRno3648   blank    500    479    504    529    561
23       0       0  H3TRno3648   blank    516    477    486    526    552
24     unk     unk  A5TRno3648     rna  12913  15194  18100  21207  24640
25     unk     unk  A6TRno3648     rna   9701  11360  13528  15809  18239
26     unk     unk  A7TRno3648     rna   5785   6726   7980   9307  10717
27     unk     unk  C5TRno3648     rna   2299   2644   3081   3557   4057

      527  ...   703   705   707   709   711   713   715   717   719   721
20    930  ...   830   678   875   915  1007  1101  1007  1320  1574  1545
21    672  ...   682   871   840   839  1048  1101  1158  1430  1453  1679
22    587  ...   801   775   910   839   923  1193  1058  1210  1332  1545
23    588  ...   712   807   805   954   965  1055  1158  1430  1393  1612
24  27935  ...  2639  2518  2520  2594  2474  2432  2418  2585  2483  2485
25  20730  ...  2224  2227  2170  2212  2223  2202  2216  2255  2361  2351
26  12190  ...  1631  1646  1715  1678  1678  1744  1914  1760  1998  2015
27   4590  ...  1097  1162  1155  1182  1300  1377  1511  1650  1514  1881

[8 rows x 107 columns]

,protein,RNA,Sample ID,Chem,517,519,521,523,525,527,...,703,705,707,709,711,713,715,717,719,721
0,500.0,500.0,A1TRno3648,prorna,13720,16037,19001,22153,25348,28684,...,2669,2582,2415,2441,2474,2432,2468,2695,2664,2754
1,500.0,500.0,A2TRno3648,prorna,12906,15065,17886,20872,23946,27118,...,2580,2453,2415,2479,2349,2432,2418,2420,2422,2620
2,500.0,500.0,A3TRno3648,prorna,13368,15641,18534,21578,24871,28142,...,2580,2647,2450,2365,2516,2570,2367,2530,2483,2620
3,250.0,250.0,B1TRno3648,prorna,6241,7287,8634,10035,11480,12993,...,1720,1582,1680,1678,1678,1744,1914,1870,1938,2217
4,250.0,250.0,B2TRno3648,prorna,6110,7080,8394,9760,11280,12679,...,1661,1614,1575,1678,1678,1698,1763,1925,1938,2015
5,250.0,250.0,B3TRno3648,prorna,5939,6940,8162,9533,10951,12403,...,1661,1711,1680,1602,1552,1698,1813,1815,2059,1881
6,125.0,125.0,C1TRno3648,prorna,3077,3550,4146,4846,5503,6198,...,1186,1227,1330,1297,1384,1514,1561,1650,1695,1814
7,125.0,125.0,C2TRno3648,prorna,2920,3331,3934,4545,5205,5865,...,1216,1162,1260,1335,1300,1377,1561,1705,1695,1948
8,125.0,125.0,C3TRno3648,prorna,3059,3499,4136,4764,5430,6141,...,1157,1194,1295,1259,1300,1331,1461,1540,1756,1948
9,62.5,62.5,D1TRno3648,prorna,1758,1982,2288,2628,2986,3331,...,1008,1033,1015,1106,1174,1285,1461,1485,1695,1612
10,62.5,62.5,D2TRno3648,prorna,1754,1942,2272,2598,2945,3283,...,919,968,945,1144,1216,1285,1410,1485,1695,1746
11,62.5,62.5,D3TRno3648,prorna,1690,1902,2188,2500,2813,3130,...,890,1001,1015,1106,1132,1285,1360,1320,1574,1545
12,31.25,31.25,E1TRno3648,prorna,1109,1215,1371,1566,1732,1906,...,830,839,980,1106,1258,1239,1310,1375,1574,1612
13,31.25,31.25,E2TRno3648,prorna,1119,1194,1364,1540,1721,1924,...,919,904,910,954,1048,1147,1360,1375,1574,1612
14,31.25,31.25,E3TRno3648,prorna,1134,1209,1384,1550,1723,1905,...,860,871,875,1030,965,1193,1360,1485,1514,1612
15,15.625,15.625,F1TRno3648,prorna,776,818,910,1011,1111,1218,...,741,904,945,1030,965,1101,1209,1430,1514,1478
16,15.625,15.625,F2TRno3648,prorna,854,894,1009,1118,1221,1336,...,890,904,980,954,1132,1147,1209,1265,1393,1545
17,15.625,15.625,F3TRno3648,prorna,830,834,939,1040,1161,1248,...,890,742,910,954,1090,1147,1158,1375,1574,1679
18,7.8125,7.8125,G1TRno3648,prorna,645,658,722,796,854,916,...,830,742,1015,992,1090,1147,1209,1375,1453,1679
19,7.8125,7.8125,G2TRno3648,prorna,655,654,730,792,849,901,...,741,871,875,1068,1048,1285,1360,1375,1574,1612
20,7.8125,7.8125,G3TRno3648,prorna,675,659,738,788,871,930,...,830,678,875,915,1007,1101,1007,1320,1574,1545
21,0,0,H1TRno3648,blank,546,533,568,605,649,672,...,682,871,840,839,1048,1101,1158,1430,1453,1679
22,0,0,H2TRno3648,blank,500,479,504,529,561,587,...,801,775,910,839,923,1193,1058,1210,1332,1545
23,0,0,H3TRno3648,blank,516,477,486,526,552,588,...,712,807,805,954,965,1055,1158,1430,1393,1612
24,unk,unk,A5TRno3648,rna,12913,15194,18100,21207,24640,27935,...,2639,2518,2520,2594,2474,2432,2418,2585,2483,2485
25,unk,unk,A6TRno3648,rna,9701,11360,13528,15809,18239,20730,...,2224,2227,2170,2212,2223,2202,2216,2255,2361,2351
26,unk,unk,A7TRno3648,rna,5785,6726,7980,9307,10717,12190,...,1631,1646,1715,1678,1678,1744,1914,1760,1998,2015
27,unk,unk,C5TRno3648,rna,2299,2644,3081,3557,4057,4590,...,1097,1162,1155,1182,1300,1377,1511,1650,1514,1881
28,unk,unk,C6TRno3648,rna,2355,2688,3140,3638,4161,4681,...,1186,1033,1190,1144,1384,1377,1461,1595,1574,1679
29,unk,unk,C7TRno3648,rna,2421,2772,3222,3714,4263,4806,...,1038,1162,1155,1221,1342,1285,1511,1650,1816,1881
30,unk,unk,E5TRno3648,rna,4365,4990,5948,6926,7926,8987,...,1364,1323,1470,1373,1468,1606,1561,1595,1938,2015
31,unk,unk,E6TRno3648,rna,3912,4493,5283,6175,7027,7983,...,1305,1323,1400,1335,1552,1285,1410,1485,1816,1948
32,unk,unk,E7TRno3648,rna,3080,3510,4111,4766,5371,6119,...,1186,1162,1155,1221,1258,1377,1561,1540,1816,1881
33,unk,unk,G5TRno3648,rna,3789,4380,5133,5904,6790,7702,...,1305,1323,1365,1297,1468,1285,1561,1705,1756,2015
34,unk,unk,G6TRno3648,rna,4978,5741,6783,7887,9039,10252,...,1483,1420,1470,1564,1468,1744,1813,1925,1816,1948
35,unk,unk,G7TRno3648,rna,5353,6178,7286,8486,9723,10991,...,1512,1485,1540,1640,1552,1652,1662,1760,1877,1881

In [2]:
pwd

'C:\\Users\\hwbst6\\OneDrive - Sheffield Hallam University\\StudentProjects\\Student projects 2022_23\\MSc\\Bhargav\\140623'

In [5]:
cd ..

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\Bhargav

In [6]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\Bhargav

18/07/2023  13:10    <DIR>          .
18/07/2023  13:10    <DIR>          ..
04/07/2023  10:52    <DIR>          04072023
07/07/2023  15:53    <DIR>          130623
20/07/2023  12:10    <DIR>          140623
28/06/2023  13:22    <DIR>          28062023
20/06/2023  14:53           847,982 An auto-adaptive background subtraction method for Raman spectra.pdf
05/06/2023  23:37           519,966 Bhargav Researchproject RA form Jan 2019 (003).docx
12/06/2023  14:17           529,432 Bhargav Sardhara RA MSc-ST-54_SMT.docx
18/07/2023  12:16         1,474,809 RNAIR23Train_002.csv
               4 File(s)      3,372,189 bytes
               6 Dir(s)  138,287,452,160 bytes free

In [7]:
cd ..

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc

In [8]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc

20/07/2023  11:28    <DIR>          .
20/07/2023  11:28    <DIR>          ..
24/05/2023  14:56           616,573 40-876961736_R1.pdf
18/07/2023  11:52            96,450 aaa1adb9-cc89-4ad6-9c7e-c81c1b18e422.pdf
29/06/2023  10:42    <DIR>          Aleena
23/05/2023  16:19            33,518 Aleena Raju Project Proposal 2023.docx
27/03/2023  11:37            31,768 ALRP Lit Review Feedback Sheet(1).docx
23/05/2023  16:25            47,093 ALRP Research Project Proposal 2023.docx
20/07/2023  11:23           435,194 Artificial intelligence-based classification of breast.pdf
18/07/2023  13:10    <DIR>          Bhargav
23/05/2023  16:26            47,224 Bhargav Project Proposal 2023.docx
05/06/2023  16:56            89,333 Bhargav UREC1 No Human Participants 2022-23v2.docx
24/05/2023  14:48            69,804 ed6d4038-b1f9-4fcf-9fa4-035dd759fc09-OrderPackageReport.pdf
25/05/2023  16:02             2,194 gc_66-502902-AF-20223_fullgc_2023-05-25-15-58-46.xls
13/07/2023  11:10    <DIR>          MML
09/02/2023  14:37            15,598 MSc projects.docx
20/07/2023  11:09    <DIR>          Nivedh
27/03/2023  14:09            25,791 Nivedh ALRP Lit Review Feedback Sheet(1).docx
23/05/2023  16:31            47,437 Nivedh Lal Project Proposal 2023.docx
20/07/2023  11:28         1,557,193 Predicting pharmaceutical crystal morphology.pdf
27/03/2023  11:38            31,915 Raju AleenaALRP Lit Review Feedback Sheet(1).docx
15/06/2023  14:15    <DIR>          Research group
03/04/2023  16:41    <DIR>          RNA kit instructions
13/07/2023  15:36    <DIR>          RNA_synthesis
12/05/2023  17:01            45,563 Students allocations.xlsx
              16 File(s)      3,192,648 bytes
               9 Dir(s)  138,288,603,136 bytes free

In [9]:
cd ..

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23

In [10]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23

14/06/2023  16:49    <DIR>          .
14/06/2023  16:49    <DIR>          ..
09/11/2022  17:48           445,908 acs.orglett.5b02839.pdf
09/11/2022  17:53           500,158 c3ra42201a.pdf
09/05/2023  09:50    <DIR>          Collins
09/11/2022  18:31             2,786 Gaba_001.cdx
15/05/2023  11:29    <DIR>          Hall
15/05/2023  14:16    <DIR>          Holmes
15/05/2023  14:53    <DIR>          Ibrahim
09/05/2023  09:51    <DIR>          Kershaw
24/01/2023  16:59            11,439 Level_6_Proj_Student emails_23.xlsx
25/05/2023  15:30            41,740 Lewis_moderator 22_23(2).docx
25/05/2023  15:30    <DIR>          Marking schemes
15/05/2023  15:59            30,399 Moderator supervisor match 20032023_2.xls.xlsx
09/11/2022  17:20         1,986,136 Molecular mechanisms of metabotropic GABAB.pdf
14/06/2023  16:55    <DIR>          Mres
20/07/2023  11:28    <DIR>          MSc
17/05/2023  11:20    <DIR>          Pawson
18/01/2023  19:13    <DIR>          Porphyrin peer learning
09/05/2023  09:51    <DIR>          Smith
18/05/2023  11:35    <DIR>          Ward
15/05/2023  19:01    <DIR>          Watson
11/05/2023  15:35    <DIR>          White
               7 File(s)      3,018,566 bytes
              16 Dir(s)  138,286,522,368 bytes free

In [11]:
cd MSc

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc

In [12]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc

20/07/2023  11:28    <DIR>          .
20/07/2023  11:28    <DIR>          ..
24/05/2023  14:56           616,573 40-876961736_R1.pdf
18/07/2023  11:52            96,450 aaa1adb9-cc89-4ad6-9c7e-c81c1b18e422.pdf
29/06/2023  10:42    <DIR>          Aleena
23/05/2023  16:19            33,518 Aleena Raju Project Proposal 2023.docx
27/03/2023  11:37            31,768 ALRP Lit Review Feedback Sheet(1).docx
23/05/2023  16:25            47,093 ALRP Research Project Proposal 2023.docx
20/07/2023  11:23           435,194 Artificial intelligence-based classification of breast.pdf
18/07/2023  13:10    <DIR>          Bhargav
23/05/2023  16:26            47,224 Bhargav Project Proposal 2023.docx
05/06/2023  16:56            89,333 Bhargav UREC1 No Human Participants 2022-23v2.docx
24/05/2023  14:48            69,804 ed6d4038-b1f9-4fcf-9fa4-035dd759fc09-OrderPackageReport.pdf
25/05/2023  16:02             2,194 gc_66-502902-AF-20223_fullgc_2023-05-25-15-58-46.xls
13/07/2023  11:10    <DIR>          MML
09/02/2023  14:37            15,598 MSc projects.docx
20/07/2023  11:09    <DIR>          Nivedh
27/03/2023  14:09            25,791 Nivedh ALRP Lit Review Feedback Sheet(1).docx
23/05/2023  16:31            47,437 Nivedh Lal Project Proposal 2023.docx
20/07/2023  11:28         1,557,193 Predicting pharmaceutical crystal morphology.pdf
27/03/2023  11:38            31,915 Raju AleenaALRP Lit Review Feedback Sheet(1).docx
15/06/2023  14:15    <DIR>          Research group
03/04/2023  16:41    <DIR>          RNA kit instructions
13/07/2023  15:36    <DIR>          RNA_synthesis
12/05/2023  17:01            45,563 Students allocations.xlsx
              16 File(s)      3,192,648 bytes
               9 Dir(s)  138,266,402,816 bytes free

In [13]:
cd MML

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML

In [14]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML

13/07/2023  11:10    <DIR>          .
13/07/2023  11:10    <DIR>          ..
24/05/2023  11:04             1,422 24052023_1.csv
06/07/2023  10:43    <DIR>          Fluorescence_data
24/05/2023  10:57             1,106 knn_settings24052023_1.txt.xml
17/05/2023  11:43                 0 New Text Document.txt
26/06/2023  16:11    <DIR>          refresher tutorial
08/06/2023  10:56            12,597 RNAfluor22Train.csv
26/06/2023  18:01           121,463 RNAUVvis22Train _II.csv
17/05/2023  11:49           123,595 RNAUVvis22Train.csv
13/07/2023  11:10           123,595 RNAUVvis22Train_2.csv
26/06/2023  15:01    <DIR>          UV_vis
26/06/2023  17:43           133,157 uvvis_unk-260623.csv
26/06/2023  18:12           130,367 uvvis_unk-260623_II.csv
               9 File(s)        647,302 bytes
               5 Dir(s)  138,266,832,896 bytes free

In [15]:
cd Fluorescence_data

C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML\Fluorescence_data

In [16]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML\Fluorescence_data

06/07/2023  10:43    <DIR>          .
06/07/2023  10:43    <DIR>          ..
05/07/2023  22:27            12,623 flu_train_001.csv
05/07/2023  23:07            12,862 flu_train_002.csv
13/07/2023  11:10            24,997 flu_train_003_for_nivedh.csv
05/07/2023  22:27            26,445 flu_unk_001.csv
05/07/2023  14:19            12,641 mml_format.csv
17/09/2022  15:00            99,086 RNA QUANTIFLUOR_005.csv
08/06/2023  10:56           152,595 RNA QUANTIFLUOR_006 20-7-22.xlsx
17/09/2022  15:00            31,619 RNA Quantifluor-001.xlsx
05/07/2023  22:31            64,894 RNA Quantifluor-003- 5-7-22.xlsx
06/07/2023  10:43           110,471 RNA Quantifluor-007 27-7-2022.xlsx
              10 File(s)        548,233 bytes
               2 Dir(s)  138,262,986,752 bytes free

In [32]:
#fourth attemp at processing outout ftom the Clario star for our ML

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from numpy import log as ln

sht_name = "TRno3575" # this is varible for sheet name/experiment number
sps_name = "RNA Quantifluor-003- 5-7-22.xlsx" # this is the spread sheet name
wel_num = 36 #number os wells used

#load in plate reader output uncomment the one you want to use

# use this if your reading in from a multisheet excel
flu_inp = pd.read_excel('RNA Quantifluor-003- 5-7-22.xlsx', sheet_name = sht_name)

# useing this if your reading from a *csv file
#flu_inp = pd.read_csv(sht_name + '.csv')

#transpose and remove some columns, these may need changeing
flu_inp= pd.DataFrame.transpose(flu_inp)
flu_inp = flu_inp.drop(axis=1, columns=[0,1,2,3])

#flu_inp.sort_index()
flu_inp = flu_inp.reset_index(drop=True)

#build well name and remove related columns
flu_inp.iloc[0:,1] = flu_inp.iloc[0:,1].astype(str)
flu_inp.iloc[0:,2] = flu_inp.iloc[0:,0].astype(str) + flu_inp.iloc[0:,1].astype(str)
flu_inp = flu_inp.drop(axis=1, columns=[4,5])
flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=0)

flu_inp.insert(1, "RNA", "")

flu_inp.iloc[0,1] = flu_inp.columns[1]          
flu_inp.insert(0, "protein", "")
flu_inp.insert(3, "Chem", "")
flu_inp.insert(3, "Sample ID", "")

n=1
#sample ID fill
while n <= wel_num: # does this number need to be a varible
    flu_inp.iloc[n,3] =  flu_inp.iloc[n,1] + sht_name
    n = n + 1

# title fill
n=0
while n <= 4:
    flu_inp.iloc[0,n] =  flu_inp.columns[n]
    n = n + 1   
    
flu_inp = pd.DataFrame.drop(flu_inp,axis=1, columns = 6)  

flu_inp.rename(columns=flu_inp.iloc[0,0:], inplace=True) # set row 0 as col titles
flu_inp = flu_inp.reset_index(drop=True)
flu_inp = pd.DataFrame.drop(flu_inp, axis=0, index=0)
flu_inp = flu_inp.reset_index(drop=True)
flu_inp.iloc[0:,1] = 0

#Design concentration

#stk_conc = 500
#exp_reps = 3
#dil_fct = 2
#std_no = 7

#n=0
#conc fill
#while n <= std_no -1:
#    n_reps = 1
#    while n_reps <= exp_reps:
#        tran_rep = (n * exp_reps + n_reps )
#        flu_inp.iloc[(tran_rep-1),1] =  stk_conc / 2**(n)
#        flu_inp.iloc[(tran_rep-1),0] =  stk_conc / 2**(n)
#        n_reps = n_reps +1
#    n = n + 1


#flu_inp.iloc[21:24,3] = "blank"
#flu_inp.iloc[24:72,0:2] = "unk"
#prorna

#flu_inp.iloc[0:21,3] = "prorna"

#print(flu_inp.loc[20:27])
#flu_train = pd.DataFrame(flu_inp.iloc[0:24,0:])  
#flu_train.to_csv("flu_train_004" + ".csv",index=False)
flu_inp.to_csv("flu_dat_" + sht_name + ".csv",index=False)
#flu_inp

In [16]:
#script for converting *.xlsx or csv data to weka compatable format

import os
import pandas as pd
import numpy as np

# input varibles go here
sht_name = "TRno3575" # this is varible for sheet name/experiment number
sps_name = "RNA Quantifluor-003- 5-7-22.xlsx" # this is the spread sheet name if your using a spread sheet

#load in plate reader output uncomment the one you want to use

# use this if your reading in from a multisheet excel
flu_inp = pd.read_excel(sps_name, sheet_name = sht_name)

# use this if your reading from a *csv file
#flu_inp = pd.read_csv(sht_name + '.csv')

#transpose and remove some columns, these may need changeing
flu_inp= pd.DataFrame.transpose(flu_inp)
flu_inp = flu_inp.drop(axis=1, columns=[0,1,2,3])

#flu_inp.sort_index()
flu_inp = flu_inp.reset_index(drop=True)

#build well name and remove related columns
flu_inp.iloc[0:,1] = flu_inp.iloc[0:,1].astype(str)
flu_inp.iloc[0:,2] = flu_inp.iloc[0:,0].astype(str) + flu_inp.iloc[0:,1].astype(str)
flu_inp = flu_inp.drop(axis=1, columns=[4,5])
flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=0)
flu_inp.insert(1, "RNA", "")
flu_inp.iloc[0,1] = flu_inp.columns[1]          
flu_inp.insert(0, "protein", "")
flu_inp.insert(3, "Chem", "")
flu_inp.insert(3, "Sample ID", "")
wel_num = len(flu_inp.index)-1

#sample ID fill
n=1
while n <= wel_num: # does this number need to be a varible
    flu_inp.iloc[n,3] =  flu_inp.iloc[n,1] + sht_name
    n = n + 1
    
# title fill
n=0
while n <= 4:
    flu_inp.iloc[0,n] =  flu_inp.columns[n]
    n = n + 1   
    
flu_inp = pd.DataFrame.drop(flu_inp,axis=1, columns = 6)  
flu_inp.rename(columns=flu_inp.iloc[0,0:], inplace=True) # set row 0 as col titles
flu_inp = flu_inp.reset_index(drop=True)
flu_inp = pd.DataFrame.drop(flu_inp, axis=0, index=0)
flu_inp = flu_inp.reset_index(drop=True)

#output results
flu_inp.to_csv("flu_dat_" + sht_name + ".csv",index=False)
flu_inp

,protein,RNA,Sample ID,Chem,517,519,521,523,525,527,...,703,705,707,709,711,713,715,717,719,721
0,,,A1TRno3575,,13720,16037,19001,22153,25348,28684,...,2669,2582,2415,2441,2474,2432,2468,2695,2664,2754
1,,,A2TRno3575,,12906,15065,17886,20872,23946,27118,...,2580,2453,2415,2479,2349,2432,2418,2420,2422,2620
2,,,A3TRno3575,,13368,15641,18534,21578,24871,28142,...,2580,2647,2450,2365,2516,2570,2367,2530,2483,2620
3,,,B1TRno3575,,6241,7287,8634,10035,11480,12993,...,1720,1582,1680,1678,1678,1744,1914,1870,1938,2217
4,,,B2TRno3575,,6110,7080,8394,9760,11280,12679,...,1661,1614,1575,1678,1678,1698,1763,1925,1938,2015
5,,,B3TRno3575,,5939,6940,8162,9533,10951,12403,...,1661,1711,1680,1602,1552,1698,1813,1815,2059,1881
6,,,C1TRno3575,,3077,3550,4146,4846,5503,6198,...,1186,1227,1330,1297,1384,1514,1561,1650,1695,1814
7,,,C2TRno3575,,2920,3331,3934,4545,5205,5865,...,1216,1162,1260,1335,1300,1377,1561,1705,1695,1948
8,,,C3TRno3575,,3059,3499,4136,4764,5430,6141,...,1157,1194,1295,1259,1300,1331,1461,1540,1756,1948
9,,,D1TRno3575,,1758,1982,2288,2628,2986,3331,...,1008,1033,1015,1106,1174,1285,1461,1485,1695,1612
10,,,D2TRno3575,,1754,1942,2272,2598,2945,3283,...,919,968,945,1144,1216,1285,1410,1485,1695,1746
11,,,D3TRno3575,,1690,1902,2188,2500,2813,3130,...,890,1001,1015,1106,1132,1285,1360,1320,1574,1545
12,,,E1TRno3575,,1109,1215,1371,1566,1732,1906,...,830,839,980,1106,1258,1239,1310,1375,1574,1612
13,,,E2TRno3575,,1119,1194,1364,1540,1721,1924,...,919,904,910,954,1048,1147,1360,1375,1574,1612
14,,,E3TRno3575,,1134,1209,1384,1550,1723,1905,...,860,871,875,1030,965,1193,1360,1485,1514,1612
15,,,F1TRno3575,,776,818,910,1011,1111,1218,...,741,904,945,1030,965,1101,1209,1430,1514,1478
16,,,F2TRno3575,,854,894,1009,1118,1221,1336,...,890,904,980,954,1132,1147,1209,1265,1393,1545
17,,,F3TRno3575,,830,834,939,1040,1161,1248,...,890,742,910,954,1090,1147,1158,1375,1574,1679
18,,,G1TRno3575,,645,658,722,796,854,916,...,830,742,1015,992,1090,1147,1209,1375,1453,1679
19,,,G2TRno3575,,655,654,730,792,849,901,...,741,871,875,1068,1048,1285,1360,1375,1574,1612
20,,,G3TRno3575,,675,659,738,788,871,930,...,830,678,875,915,1007,1101,1007,1320,1574,1545
21,,,H1TRno3575,,546,533,568,605,649,672,...,682,871,840,839,1048,1101,1158,1430,1453,1679
22,,,H2TRno3575,,500,479,504,529,561,587,...,801,775,910,839,923,1193,1058,1210,1332,1545
23,,,H3TRno3575,,516,477,486,526,552,588,...,712,807,805,954,965,1055,1158,1430,1393,1612
24,,,A5TRno3575,,12913,15194,18100,21207,24640,27935,...,2639,2518,2520,2594,2474,2432,2418,2585,2483,2485
25,,,A6TRno3575,,9701,11360,13528,15809,18239,20730,...,2224,2227,2170,2212,2223,2202,2216,2255,2361,2351
26,,,A7TRno3575,,5785,6726,7980,9307,10717,12190,...,1631,1646,1715,1678,1678,1744,1914,1760,1998,2015
27,,,C5TRno3575,,2299,2644,3081,3557,4057,4590,...,1097,1162,1155,1182,1300,1377,1511,1650,1514,1881
28,,,C6TRno3575,,2355,2688,3140,3638,4161,4681,...,1186,1033,1190,1144,1384,1377,1461,1595,1574,1679
29,,,C7TRno3575,,2421,2772,3222,3714,4263,4806,...,1038,1162,1155,1221,1342,1285,1511,1650,1816,1881
30,,,E5TRno3575,,4365,4990,5948,6926,7926,8987,...,1364,1323,1470,1373,1468,1606,1561,1595,1938,2015
31,,,E6TRno3575,,3912,4493,5283,6175,7027,7983,...,1305,1323,1400,1335,1552,1285,1410,1485,1816,1948
32,,,E7TRno3575,,3080,3510,4111,4766,5371,6119,...,1186,1162,1155,1221,1258,1377,1561,1540,1816,1881
33,,,G5TRno3575,,3789,4380,5133,5904,6790,7702,...,1305,1323,1365,1297,1468,1285,1561,1705,1756,2015
34,,,G6TRno3575,,4978,5741,6783,7887,9039,10252,...,1483,1420,1470,1564,1468,1744,1813,1925,1816,1948
35,,,G7TRno3575,,5353,6178,7286,8486,9723,10991,...,1512,1485,1540,1640,1552,1652,1662,1760,1877,1881

In [12]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4632-2130

 Directory of C:\Users\hwbst6\OneDrive - Sheffield Hallam University\StudentProjects\Student projects 2022_23\MSc\MML\Fluorescence_data

20/07/2023  15:39    <DIR>          .
20/07/2023  15:39    <DIR>          ..
20/07/2023  15:47            19,356 flu_dat_TRno3575.csv
20/07/2023  15:55             8,167 flu_dat_TRno4427.csv
01/08/2023  11:32             8,057 flu_dat_TRno4428.csv
05/07/2023  22:27            12,623 flu_train_001.csv
20/07/2023  12:25            12,953 flu_train_002.csv
13/07/2023  11:10            24,997 flu_train_003_for_nivedh.csv
20/07/2023  15:49            13,040 flu_train_004.csv
20/07/2023  15:49            19,827 flu_TRno3575.csv
20/07/2023  12:25            40,383 flu_TRno3648.csv
05/07/2023  22:27            26,445 flu_unk_001.csv
05/07/2023  14:19            12,641 mml_format.csv
17/09/2022  15:00            99,086 RNA QUANTIFLUOR_005.csv
08/06/2023  10:56           152,595 RNA QUANTIFLUOR_006 20-7-22.xlsx
17/09/2022  15:00            31,619 RNA Quantifluor-001.xlsx
20/07/2023  15:23            65,016 RNA Quantifluor-003- 5-7-22.xlsx
06/07/2023  10:43           110,471 RNA Quantifluor-007 27-7-2022.xlsx
20/07/2023  10:29            10,929 TRno4427.CSV
20/07/2023  10:29            10,811 TRno4428.CSV
              18 File(s)        679,016 bytes
               2 Dir(s)  143,721,046,016 bytes free

In [27]:
#script for converting *.xlsx or csv data to weka compatable format

import os
import pandas as pd
import numpy as np

# input varibles go here
sht_name = "TRno3575" # this is varible for sheet name/experiment number
sps_name = "RNA Quantifluor-003- 5-7-22.xlsx" # this is the spread sheet name if your using a spread sheet
flu_inp= pd.DataFrame()
#load in plate reader output uncomment the one you want to use
try:
    # use this if your reading in from a multisheet excel
    flu_inp = pd.read_excel(sps_name, sheet_name = sht_name)

    # use this if your reading from a *csv file
    #flu_inp = pd.read_csv(sht_name + '.csv')
except PermissionError:
    print('The file we are trying to open may be open in another program, please close and try again!')
    

try: #transpose and remove some columns, these may need changeing
    flu_inp= pd.DataFrame.transpose(flu_inp)
    flu_inp = flu_inp.drop(axis=1, columns=[0,1,2,3])
except KeyError:
    print('Check the your input file!')
try:    #flu_inp.sort_index()
    flu_inp = flu_inp.reset_index(drop=True)
    #build well name and remove related columns
    flu_inp.iloc[0:,1] = flu_inp.iloc[0:,1].astype(str)
    flu_inp.iloc[0:,2] = flu_inp.iloc[0:,0].astype(str) + flu_inp.iloc[0:,1].astype(str)
    flu_inp = flu_inp.drop(axis=1, columns=[4,5])
    flu_inp = pd.DataFrame.drop(flu_inp,axis=0, index=0)
    flu_inp.insert(1, "RNA", "")
    flu_inp.iloc[0,1] = flu_inp.columns[1]          
    flu_inp.insert(0, "protein", "")
    flu_inp.insert(3, "Chem", "")
    flu_inp.insert(3, "Sample ID", "")
    wel_num = len(flu_inp.index)-1
#sample ID fill
    n=1
    while n <= wel_num: # does this number need to be a varible
        flu_inp.iloc[n,3] =  flu_inp.iloc[n,1] + sht_name
        n = n + 1   
# title fill
    n=0
    while n <= 4:
        flu_inp.iloc[0,n] =  flu_inp.columns[n]
        n = n + 1   
except IndexError:
    print('Check the your input file!')
try:    
    flu_inp = pd.DataFrame.drop(flu_inp,axis=1, columns = 6)  
    flu_inp.rename(columns=flu_inp.iloc[0,0:], inplace=True) # set row 0 as col titles
    flu_inp = flu_inp.reset_index(drop=True)
    flu_inp = pd.DataFrame.drop(flu_inp, axis=0, index=0)
    flu_inp = flu_inp.reset_index(drop=True)
except KeyError:
    print('Check the your input file!')
try: #output results
    flu_inp.to_csv("flu_dat_" + sht_name + ".csv",index=False)
    print(flu_inp)
except PermissionError:
    print('The file we are trying to open may be open in another program, please close and try again!')

   protein RNA   Sample ID Chem    517    519    521    523    525    527  \
0               A1TRno3575       13720  16037  19001  22153  25348  28684
1               A2TRno3575       12906  15065  17886  20872  23946  27118
2               A3TRno3575       13368  15641  18534  21578  24871  28142
3               B1TRno3575        6241   7287   8634  10035  11480  12993
4               B2TRno3575        6110   7080   8394   9760  11280  12679
5               B3TRno3575        5939   6940   8162   9533  10951  12403
6               C1TRno3575        3077   3550   4146   4846   5503   6198
7               C2TRno3575        2920   3331   3934   4545   5205   5865
8               C3TRno3575        3059   3499   4136   4764   5430   6141
9               D1TRno3575        1758   1982   2288   2628   2986   3331
10              D2TRno3575        1754   1942   2272   2598   2945   3283
11              D3TRno3575        1690   1902   2188   2500   2813   3130
12              E1TRno3575        1109   1215   1371   1566   1732   1906
13              E2TRno3575        1119   1194   1364   1540   1721   1924
14              E3TRno3575        1134   1209   1384   1550   1723   1905
15              F1TRno3575         776    818    910   1011   1111   1218
16              F2TRno3575         854    894   1009   1118   1221   1336
17              F3TRno3575         830    834    939   1040   1161   1248
18              G1TRno3575         645    658    722    796    854    916
19              G2TRno3575         655    654    730    792    849    901
20              G3TRno3575         675    659    738    788    871    930
21              H1TRno3575         546    533    568    605    649    672
22              H2TRno3575         500    479    504    529    561    587
23              H3TRno3575         516    477    486    526    552    588
24              A5TRno3575       12913  15194  18100  21207  24640  27935
25              A6TRno3575        9701  11360  13528  15809  18239  20730
26              A7TRno3575        5785   6726   7980   9307  10717  12190
27              C5TRno3575        2299   2644   3081   3557   4057   4590
28              C6TRno3575        2355   2688   3140   3638   4161   4681
29              C7TRno3575        2421   2772   3222   3714   4263   4806
30              E5TRno3575        4365   4990   5948   6926   7926   8987
31              E6TRno3575        3912   4493   5283   6175   7027   7983
32              E7TRno3575        3080   3510   4111   4766   5371   6119
33              G5TRno3575        3789   4380   5133   5904   6790   7702
34              G6TRno3575        4978   5741   6783   7887   9039  10252
35              G7TRno3575        5353   6178   7286   8486   9723  10991

    ...   703   705   707   709   711   713   715   717   719   721
0   ...  2669  2582  2415  2441  2474  2432  2468  2695  2664  2754
1   ...  2580  2453  2415  2479  2349  2432  2418  2420  2422  2620
2   ...  2580  2647  2450  2365  2516  2570  2367  2530  2483  2620
3   ...  1720  1582  1680  1678  1678  1744  1914  1870  1938  2217
4   ...  1661  1614  1575  1678  1678  1698  1763  1925  1938  2015
5   ...  1661  1711  1680  1602  1552  1698  1813  1815  2059  1881
6   ...  1186  1227  1330  1297  1384  1514  1561  1650  1695  1814
7   ...  1216  1162  1260  1335  1300  1377  1561  1705  1695  1948
8   ...  1157  1194  1295  1259  1300  1331  1461  1540  1756  1948
9   ...  1008  1033  1015  1106  1174  1285  1461  1485  1695  1612
10  ...   919   968   945  1144  1216  1285  1410  1485  1695  1746
11  ...   890  1001  1015  1106  1132  1285  1360  1320  1574  1545
12  ...   830   839   980  1106  1258  1239  1310  1375  1574  1612
13  ...   919   904   910   954  1048  1147  1360  1375  1574  1612
14  ...   860   871   875  1030   965  1193  1360  1485  1514  1612
15  ...   741   904   945  1030   965  1101  1209  1430  1514  1478
16  ...   890   904   980   954  1132  1147  1209  1265  1393  1545
17  ...   890   742   910   954  1090  1147  1158  1375  1574  1679
18  ...   830   742  1015   992  1090  1147  1209  1375  1453  1679
19  ...   741   871   875  1068  1048  1285  1360  1375  1574  1612
20  ...   830   678   875   915  1007  1101  1007  1320  1574  1545
21  ...   682   871   840   839  1048  1101  1158  1430  1453  1679
22  ...   801   775   910   839   923  1193  1058  1210  1332  1545
23  ...   712   807   805   954   965  1055  1158  1430  1393  1612
24  ...  2639  2518  2520  2594  2474  2432  2418  2585  2483  2485
25  ...  2224  2227  2170  2212  2223  2202  2216  2255  2361  2351
26  ...  1631  1646  1715  1678  1678  1744  1914  1760  1998  2015
27  ...  1097  1162  1155  1182  1300  1377  1511  1650  1514  1881
28  ...  1186  1033  1190  1144  1384  1377  1461  1595  1574  1679
29  ...  1038  1162  1155  1221  1342  1285  1511  1650  1816  1881
30  ...  1364  1323  1470  1373  1468  1606  1561  1595  1938  2015
31  ...  1305  1323  1400  1335  1552  1285  1410  1485  1816  1948
32  ...  1186  1162  1155  1221  1258  1377  1561  1540  1816  1881
33  ...  1305  1323  1365  1297  1468  1285  1561  1705  1756  2015
34  ...  1483  1420  1470  1564  1468  1744  1813  1925  1816  1948
35  ...  1512  1485  1540  1640  1552  1652  1662  1760  1877  1881

[36 rows x 107 columns]